id: fighter-f

display: "fighter-f"

gender: female

stage: 1

requires-level: 10

parent: adventurer

combat-style: melee

armor-mastery: HEAVY

external: false

base-attributes:
  strength:  9
  spirit:   9
  intellect: 2
  vitality:  8

default-skin: alex
