id: brawler-m

display: "brawler-m"
gender: male

stage: 2

requires-level: 20

parent: fighter-m

combat-style: assassin

armor-mastery: LEATHER

external: false

base-attributes:
  strength:  12
  spirit:   14
  intellect: 4
  vitality:  12

default-skin: steve
