id: demolisher-f

display: "demolisher-f"
gender: female

stage: 2

requires-level: 20

parent: gunner-f

combat-style: ranged

armor-mastery: LEATHER

external: false

base-attributes:
  strength:  7
  spirit:   16
  intellect: 6
  vitality:  9

default-skin: alex
