id: enchantress

display: "enchantress"

gender: female

stage: 2

requires-level: 20

parent: mage-f

combat-style: magic

armor-mastery: CLOTH

external: false

base-attributes:
  strength:  2
  spirit:   7
  intellect: 22
  vitality:  7

default-skin: alex
