id: hunter

display: "hunter"
gender: female

stage: 2

requires-level: 20

parent: archer

combat-style: ranged

armor-mastery: LEATHER

external: false

base-attributes:
  strength:  8
  spirit:   17
  intellect: 6
  vitality:  7

default-skin: alex
