id: hybrid-piper

display: "hybrid-piper"
gender: male

stage: 2

requires-level: 20

parent: gunner-m

combat-style: melee

armor-mastery: HEAVY

external: false

base-attributes:
  strength:  12
  spirit:   12
  intellect: 5
  vitality:  13

default-skin: steve
