id: ronin

display: "ronin"
gender: female

stage: 2

requires-level: 20

parent: slayer-f

combat-style: melee

armor-mastery: HEAVY

external: false

base-attributes:
  strength:  15
  spirit:   12
  intellect: 4
  vitality:  11

default-skin: alex
