id: blade-shadow-f

display: "blade-shadow-f"
gender: female

stage: 2

requires-level: 20

parent: slayer-f

combat-style: assassin

armor-mastery: LEATHER

external: false

base-attributes:
  strength:  11
  spirit:   16
  intellect: 4
  vitality:  11

default-skin: alex
