id: nen-master-f

display: "nen-master-f"

gender: female

stage: 2

requires-level: 20

parent: fighter-f

combat-style: magic

armor-mastery: CLOTH

external: false

base-attributes:
  strength:  10
  spirit:   11
  intellect: 11
  vitality:  10

default-skin: alex
