id: street-fighter-m

display: "street-fighter-m"
gender: male

stage: 2

requires-level: 20

parent: fighter-m

combat-style: melee

armor-mastery: HEAVY

external: false

base-attributes:
  strength:  16
  spirit:   10
  intellect: 3
  vitality:  13

default-skin: steve
