id: sword-shadow

display: "sword-shadow"
gender: male

stage: 2

requires-level: 20

parent: slayer

combat-style: assassin

armor-mastery: LEATHER

external: false

base-attributes:
  strength:  12
  spirit:   15
  intellect: 5
  vitality:  10

default-skin: steve
