id: traveler

display: "traveler"
gender: female

stage: 2

requires-level: 20

parent: archer

combat-style: ranged

armor-mastery: LEATHER

external: false

base-attributes:
  strength:  6
  spirit:   18
  intellect: 7
  vitality:  7

default-skin: alex
